#include "web_page.h"

static const char k_dashboard_page[] =
    "<!doctype html><html><head><meta charset='utf-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>Cat Wheel Live</title>"
    "<style>"
    ":root{--bg:#eef2f7;--surface:#ffffff;--surface2:#f5f8ff;--text:#1b2430;--muted:#5f6e85;--border:#d8e0ef;--accent:#2f6fed;--accent2:#1fb677;"
    "--wood-rim:#8b5a2b;--wood-mid:#b47a45;--wood-light:#c8925b;--wood-dark:rgba(90,56,30,.45);}"
    "@media (prefers-color-scheme: dark){:root{--bg:#0f141b;--surface:#171e28;--surface2:#101823;--text:#e8eef7;--muted:#9fb0c7;--border:#2a3648;--accent:#6ea8ff;--accent2:#43d696;"
    "--wood-rim:#9a6b3e;--wood-mid:#b88455;--wood-light:#d0a06d;--wood-dark:rgba(66,41,22,.55);}}"
    "*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:'Segoe UI',Tahoma,Arial,sans-serif}"
    "main{max-width:980px;margin:0 auto;padding:12px}.top{display:flex;align-items:center;justify-content:space-between;gap:8px}"
    "h2,h3{margin:0 0 10px 0}section{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:12px;margin:10px 0}"
    "a.btn{display:inline-block;text-decoration:none;background:var(--accent);color:#fff;padding:8px 12px;border-radius:10px;font-weight:600}"
    ".hero{display:grid;grid-template-columns:1fr 1fr;gap:12px}.hero-info{display:grid;gap:8px;align-content:start}"
    ".k{font-size:.78rem;color:var(--muted);text-transform:uppercase;letter-spacing:.05em}.v{font-size:1.45rem;font-weight:700}"
    ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:8px}"
    ".card{background:var(--surface2);border:1px solid var(--border);border-radius:10px;padding:10px}"
    ".pet-stage{position:relative;display:grid;place-items:center;min-height:210px}"
    ".wheel{--wheel-dur:3.00s;width:min(58vw,230px);aspect-ratio:1;border-radius:50%;position:relative;"
    "background:repeating-conic-gradient(from 0deg,var(--wood-light) 0 8deg,var(--wood-mid) 8deg 16deg,var(--wood-rim) 16deg 24deg);"
    "animation:wheel-spin var(--wheel-dur) linear infinite;box-shadow:inset 0 0 0 5px var(--wood-dark),inset 0 0 0 10px var(--wood-light),0 8px 16px rgba(40,20,8,.24)}"
    ".wheel:before{content:'';position:absolute;inset:24px;border-radius:50%;background:var(--bg);box-shadow:inset 0 0 0 2px rgba(139,90,43,.45)}"
    ".cat-svg{--cat-dur:.95s;--run:running;position:absolute;left:46%;bottom:8%;width:min(44vw,176px);transform:translateX(-50%);"
    "animation:cat-bob var(--cat-dur) ease-in-out infinite;animation-play-state:var(--run);filter:drop-shadow(0 2px 0 rgba(0,0,0,.12))}"
    ".cat-svg .fur{fill:#f1a262}.cat-svg .fur2{fill:#5f2f16}.cat-svg .belly{fill:#ffe7d2}"
    ".cat-svg .line{stroke:#6b3f23;stroke-width:2.2;fill:none;stroke-linecap:round;stroke-linejoin:round}"
    ".cat-svg .face{fill:#1d2530}.cat-svg .nose{fill:#d7708a}.cat-svg .ear{fill:#f8bfab}.cat-svg .paw{fill:#e48f52}"
    ".cat-svg .tail{transform-origin:155px 66px;animation:tail-swing calc(var(--cat-dur)*1.05) ease-in-out infinite;animation-play-state:var(--run)}"
    ".cat-svg .legs-a{transform-origin:96px 100px;animation:legs-a var(--cat-dur) ease-in-out infinite;animation-play-state:var(--run)}"
    ".cat-svg .legs-b{transform-origin:112px 100px;animation:legs-b var(--cat-dur) ease-in-out infinite;animation-play-state:var(--run)}"
    "canvas{width:100%;max-width:100%;height:auto;border:1px solid var(--border);border-radius:10px;background:var(--surface2);touch-action:none}"
    "@keyframes wheel-spin{from{transform:rotate(0)}to{transform:rotate(-360deg)}}"
    "@keyframes cat-bob{0%,100%{transform:translateX(-50%) translateY(0)}50%{transform:translateX(-50%) translateY(-3px)}}"
    "@keyframes tail-swing{0%,100%{transform:rotate(14deg)}50%{transform:rotate(-10deg)}}"
    "@keyframes legs-a{0%,100%{transform:rotate(10deg)}50%{transform:rotate(-10deg)}}"
    "@keyframes legs-b{0%,100%{transform:rotate(-10deg)}50%{transform:rotate(10deg)}}"
    "@media (max-width:780px){.hero{grid-template-columns:1fr}.v{font-size:1.25rem}}"
    "</style></head><body><main>"
    "<div class='top'><h2>Cat Wheel Live</h2><a class='btn' href='/settings' data-i18n='nav_settings'>Settings</a></div>"
    "<section class='hero'>"
    "<div class='pet-stage'>"
    "<div class='wheel' id='wheel_anim'></div>"
    "<svg class='cat-svg' id='cat_anim' viewBox='0 0 180 120' aria-hidden='true'>"
    "<g class='tail'><path d='M145 71 Q167 58 170 39 Q166 29 156 35 Q160 46 141 61 Z' class='fur'/>"
    "<path d='M145 71 Q167 58 170 39 Q166 29 156 35 Q160 46 141 61' class='line'/></g>"
    "<g class='legs-a'><rect x='79' y='95' width='12' height='30' rx='6' class='paw'/><rect x='125' y='90' width='12' height='30' rx='6' class='paw'/></g>"
    "<g class='legs-b'><rect x='95' y='95' width='12' height='30' rx='6' class='paw'/><rect x='140' y='88' width='12' height='30' rx='6' class='paw'/></g>"
    "<ellipse cx='110' cy='74' rx='50' ry='29' class='fur'/>"
    "<ellipse cx='110' cy='95' rx='23' ry='8' class='belly'/>"
    "<ellipse cx='84' cy='70' rx='7' ry='4' class='fur2'/>"
    "<ellipse cx='95' cy='57' rx='6' ry='3.5' class='fur2'/>"
    "<ellipse cx='119' cy='70' rx='7.5' ry='4.2' class='fur2'/>"
    "<ellipse cx='122' cy='60' rx='6' ry='3.4' class='fur2'/>"
    "<ellipse cx='140' cy='65' rx='6.8' ry='3.8' class='fur2'/>"
    "<ellipse cx='143' cy='83' rx='5.8' ry='3.4' class='fur2'/>"
    "<ellipse cx='124' cy='81' rx='6.2' ry='3.6' class='fur2'/>"
    "<ellipse cx='101' cy='70' rx='5.6' ry='3.2' class='fur2'/>"
    "<ellipse cx='98' cy='82' rx='5.4' ry='3.1' class='fur2'/>"
    "<circle cx='58' cy='66' r='24' class='fur'/>"
    "<polygon points='41,55 47,35 58,52' class='fur'/><polygon points='58,52 68,34 75,55' class='fur'/>"
    "<polygon points='47,52 51,42 57,52' class='ear'/><polygon points='61,52 66,41 71,52' class='ear'/>"
    "<ellipse cx='50' cy='67' rx='2.6' ry='2.3' class='face'/><ellipse cx='63' cy='67' rx='2.6' ry='2.3' class='face'/>"
    "<path d='M55 71 L58 71 L56.5 73.5 Z' class='nose'/>"
    "<path d='M51 74 Q56.5 78 62 74' class='line'/>"
    "<path d='M45 69 L34 67 M45 73 L34 73 M68 69 L79 67 M68 73 L79 73' class='line'/>"
    "</svg>"
    "</div>"
    "<div class='hero-info'>"
    "<div class='k' data-i18n='hero_speed_label'>Current Speed</div><div class='v' id='v_now'>- km/h</div>"
    "<div class='k' data-i18n='hero_status_label'>Status</div><div class='v' id='v_anim_state'>idle</div>"
    "<div class='k' data-i18n='hero_wifi_label'>WiFi</div><div class='v' id='v_wifi'>-</div>"
    "<div class='k' data-i18n='hero_time_label'>Time</div><div class='v' id='v_time'>-</div>"
    "</div>"
    "</section>"
    "<section><h3 data-i18n='section_live_title'>Live Values</h3><div class='grid'>"
    "<div class='card'><div class='k' data-i18n='lbl_session_dist'>Session Distance</div><div class='v' id='v_session_dist'>-</div></div>"
    "<div class='card'><div class='k' data-i18n='lbl_session_dur'>Session Duration</div><div class='v' id='v_session_dur'>-</div></div>"
    "<div class='card'><div class='k' data-i18n='lbl_today'>Distance Today</div><div class='v' id='v_today'>-</div></div>"
    "<div class='card'><div class='k' data-i18n='lbl_top_today'>Top Speed Today</div><div class='v' id='v_top_today'>-</div></div>"
    "</div></section>"
    "<section><h3 data-i18n='section_stats_title'>Statistics</h3><div class='grid'>"
    "<div class='card'><div class='k' data-i18n='lbl_total'>Total Distance</div><div class='v' id='v_total'>-</div></div>"
    "<div class='card'><div class='k' data-i18n='lbl_top'>Top Speed</div><div class='v' id='v_top'>-</div></div>"
    "</div></section>"
    "<section><h3 data-i18n='section_graph_title'>Session Graph</h3><canvas id='cv' width='920' height='220'></canvas></section>"
    "<script>"
    "const E=id=>document.getElementById(id);"
    "const F=(n,d=2)=>Number(n||0).toFixed(d);"
    "const I18N={"
    "en:{nav_settings:'Settings',hero_speed_label:'Current Speed',hero_status_label:'Status',hero_wifi_label:'WiFi',hero_time_label:'Time',"
    "section_live_title:'Live Values',lbl_session_dist:'Session Distance',lbl_session_dur:'Session Duration',lbl_today:'Distance Today',lbl_top_today:'Top Speed Today',"
    "section_stats_title:'Statistics',lbl_total:'Total Distance',lbl_top:'Top Speed',section_graph_title:'Session Graph',"
    "anim_running:'running',anim_idle:'idle',time_sync_pending:'Time sync pending',graph_no_sessions:'No sessions',graph_yaxis:'Distance',graph_xaxis:'Time',"
    "graph_tip_time:'Time',graph_tip_dist:'Dist',graph_tip_dur:'Duration',graph_tip_top:'Top',graph_tip_avg:'Avg',graph_range:'Range',graph_nav_hint:'Mouse wheel, drag or swipe',graph_load_error:'Graph load error'},"
    "de:{nav_settings:'Einstellungen',hero_speed_label:'Aktuelle Geschwindigkeit',hero_status_label:'Status',hero_wifi_label:'WLAN',hero_time_label:'Zeit',"
    "section_live_title:'Live Werte',lbl_session_dist:'Session Distanz',lbl_session_dur:'Session Dauer',lbl_today:'Distanz heute',lbl_top_today:'Top Speed heute',"
    "section_stats_title:'Statistik',lbl_total:'Total Distanz',lbl_top:'Top Speed',section_graph_title:'Session Verlauf',"
    "anim_running:'laeuft',anim_idle:'steht',time_sync_pending:'Zeit wird synchronisiert',graph_no_sessions:'Keine Sessions',graph_yaxis:'Distanz',graph_xaxis:'Zeit',"
    "graph_tip_time:'Zeit',graph_tip_dist:'Dist',graph_tip_dur:'Dauer',graph_tip_top:'Top',graph_tip_avg:'Avg',graph_range:'Zeitraum',graph_nav_hint:'Mausrad, Ziehen oder Wischen',graph_load_error:'Graph Fehler'}};"
    "let LANG='en';"
    "const T=k=>((I18N[LANG]&&I18N[LANG][k])||I18N.en[k]||k);"
    "function applyLanguage(lang){"
    " LANG=(lang==='de')?'de':'en';"
    " localStorage.setItem('cw_lang',LANG);"
    " document.documentElement.lang=LANG;"
    " document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.getAttribute('data-i18n'); if(key){el.textContent=T(key);}});"
    " renderGraph();"
    "}"
    "async function loadLanguage(){"
    " const cached=localStorage.getItem('cw_lang');"
    " if(cached==='de'||cached==='en'){applyLanguage(cached);}"
    " try{const r=await fetch('/api/config'); if(r.ok){const c=await r.json(); applyLanguage(c.language||'en');}}catch(_e){}"
    "}"
    "function setAnim(speed){"
    " const s=Math.max(0,Math.min(40,Number(speed)||0));"
    " const run=s>0.08;"
    " const wheelDur=(3.40-(2.80*(s/40)));"
    " const catDur=(1.05-(0.70*(s/40)));"
    " const w=E('wheel_anim'); const c=E('cat_anim');"
    " w.style.setProperty('--wheel-dur',wheelDur.toFixed(2)+'s');"
    " c.style.setProperty('--cat-dur',catDur.toFixed(2)+'s');"
    " c.style.setProperty('--run',run?'running':'paused');"
    " w.style.animationPlayState=run?'running':'paused';"
    " c.style.animationPlayState=run?'running':'paused';"
    " E('v_anim_state').textContent=run?T('anim_running'):T('anim_idle');"
    "}"
    "async function tick(){"
    " const r=await fetch('/api/status'); if(!r.ok) return; const d=await r.json();"
    " E('v_now').textContent=F(d.current_speed_kmh,2)+' km/h';"
    " E('v_session_dist').textContent=F(d.session_distance_m,1)+' m';"
    " E('v_session_dur').textContent=(d.session_duration_s||0)+' s';"
    " E('v_wifi').textContent=d.wifi_connected?('STA '+(d.sta_ip||'')):'AP';"
    " E('v_time').textContent=d.time_synced?(d.now_iso||'-'):T('time_sync_pending');"
    " E('v_total').textContent=F(d.total_distance_m/1000,3)+' km';"
    " E('v_today').textContent=F(d.distance_today_m/1000,3)+' km';"
    " E('v_top').textContent=F(d.top_speed_kmh,2)+' km/h';"
    " E('v_top_today').textContent=F(d.top_speed_today_kmh,2)+' km/h';"
    " setAnim(d.current_speed_kmh);"
    "}"
    "const graphState={sessions:[],start:0,window:60,hover:-1,layout:null,drag:false,dragX:0,dragStart:0,error:'',stickLatest:true};"
    "const clampI=(v,min,max)=>Math.max(min,Math.min(max,v));"
    "function graphTimeLabel(rec,idx){"
    " if(rec&&rec.start_epoch_s){const dt=new Date((rec.start_epoch_s||0)*1000); if(!isNaN(dt.getTime())){const hh=String(dt.getHours()).padStart(2,'0'); const mm=String(dt.getMinutes()).padStart(2,'0'); return hh+':'+mm;}}"
    " if(rec&&rec.start_iso&&rec.start_iso.length>=16){return rec.start_iso.substring(11,16);} return '#'+String(idx+1);"
    "}"
    "function graphClientPoint(ev){"
    " if(ev&&ev.touches&&ev.touches.length){return {x:ev.touches[0].clientX,y:ev.touches[0].clientY};}"
    " if(ev&&ev.changedTouches&&ev.changedTouches.length){return {x:ev.changedTouches[0].clientX,y:ev.changedTouches[0].clientY};}"
    " return {x:ev.clientX,y:ev.clientY};"
    "}"
    "function graphPointerIndex(ev){"
    " const c=E('cv'); const l=graphState.layout; if(!c||!l) return -1;"
    " const rect=c.getBoundingClientRect(); const p=graphClientPoint(ev); const x=(p.x-rect.left)*(c.width/rect.width); const y=(p.y-rect.top)*(c.height/rect.height);"
    " if(x<l.L||x>(l.L+l.pw)||y<l.T||y>(l.T+l.ph)) return -1;"
    " const i=Math.floor((x-l.L)/l.bw); if(i<0||i>=l.visibleCount) return -1; return l.visibleStart+i;"
    "}"
    "function renderGraph(){"
    " const c=E('cv'); if(!c) return; const g=c.getContext('2d'); g.clearRect(0,0,c.width,c.height);"
    " const all=graphState.sessions||[];"
    " const cs=getComputedStyle(document.documentElement); const stroke=cs.getPropertyValue('--border').trim(); const fill=cs.getPropertyValue('--accent').trim(); const txt=cs.getPropertyValue('--text').trim(); const muted=cs.getPropertyValue('--muted').trim()||txt;"
    " g.font='12px Segoe UI,Tahoma,Arial,sans-serif'; g.lineWidth=1;"
    " const L=58,TOP=12,R=14,B=38; const pw=c.width-L-R; const ph=c.height-TOP-B;"
    " if(!all.length){g.strokeStyle=stroke; g.strokeRect(L,TOP,pw,ph); g.fillStyle=txt; g.textAlign='center'; g.textBaseline='middle'; g.fillText(T('graph_no_sessions'),c.width/2,c.height/2-6); if(graphState.error){g.fillStyle='#ff6961'; g.fillText(T('graph_load_error'),c.width/2,c.height/2+12);} g.textAlign='start'; g.textBaseline='alphabetic'; graphState.layout=null; return;}"
    " graphState.window=Math.max(10,Math.min(60,all.length));"
    " const maxStart=Math.max(0,all.length-graphState.window); graphState.start=clampI(graphState.start,0,maxStart);"
    " const s=all.slice(graphState.start,graphState.start+graphState.window);"
    " if(graphState.hover<graphState.start||graphState.hover>=(graphState.start+s.length)){graphState.hover=-1;}"
    " const maxM=Math.max(...s.map(x=>{const v=Number(x&&x.distance_m); return Number.isFinite(v)?v:0;}),1); const useKm=maxM>=1000; const unit=useKm?'km':'m'; const maxV=useKm?(maxM/1000):maxM;"
    " g.strokeStyle=stroke; g.strokeRect(L,TOP,pw,ph);"
    " g.fillStyle=txt; g.fillText(T('graph_yaxis')+' ('+unit+')',L,TOP-2); g.fillText(T('graph_xaxis'),L+pw-24,c.height-6);"
    " g.fillStyle=muted; g.strokeStyle=stroke;"
    " for(let i=0;i<=4;i++){const y=TOP+ph-(i*ph/4); g.beginPath(); g.moveTo(L,y); g.lineTo(L+pw,y); g.stroke(); const v=(maxV*i/4); const n=(v>=10)?Math.round(v):Number(v.toFixed(1)); g.fillText(String(n)+' '+unit,6,y+4);}"
    " const bw=pw/Math.max(1,s.length); g.fillStyle=fill;"
    " s.forEach((x,i)=>{const raw=Number(x&&x.distance_m); const distM=Number.isFinite(raw)?raw:0; const v=useKm?(distM/1000):distM; const h=(v/maxV)*ph; const bx=L+i*bw+0.5; g.fillRect(bx,TOP+ph-h,Math.max(1,bw-1),h); if((graphState.start+i)===graphState.hover){g.strokeStyle=txt; g.strokeRect(bx,TOP+ph-h,Math.max(1,bw-1),h); g.strokeStyle=stroke;}});"
    " const idxs=[0,Math.floor((s.length-1)/2),s.length-1].filter((v,i,a)=>a.indexOf(v)===i); g.fillStyle=txt; g.strokeStyle=stroke;"
    " idxs.forEach(idx=>{const x=L+(idx+0.5)*bw; g.beginPath(); g.moveTo(x,TOP+ph); g.lineTo(x,TOP+ph+5); g.stroke(); const rec=s[idx]||{}; const label=graphTimeLabel(rec,graphState.start+idx); const tw=g.measureText(label).width; const lx=Math.max(L,Math.min(L+pw-tw,x-(tw/2))); g.fillText(label,lx,c.height-18);});"
    " graphState.layout={L,T:TOP,pw,ph,bw,visibleStart:graphState.start,visibleCount:s.length,useKm,unit,maxV};"
    " if(graphState.hover>=graphState.start&&graphState.hover<(graphState.start+s.length)){"
    "   const i=graphState.hover-graphState.start; const rec=s[i]||{}; const x=L+(i+0.5)*bw;"
    "   g.strokeStyle=fill; g.beginPath(); g.moveTo(x,TOP); g.lineTo(x,TOP+ph); g.stroke();"
    "   const distRaw=Number(rec&&rec.distance_m); const distM=Number.isFinite(distRaw)?distRaw:0; const dist=useKm?(distM/1000):distM;"
    "   const lines=[T('graph_tip_time')+' '+graphTimeLabel(rec,graphState.hover),T('graph_tip_dist')+' '+dist.toFixed(useKm?3:1)+' '+unit,T('graph_tip_dur')+' '+String(Math.round(rec.duration_s||0))+' s',T('graph_tip_top')+' '+Number(rec.top_speed_kmh||0).toFixed(1)+' km/h',T('graph_tip_avg')+' '+Number(rec.avg_speed_kmh||0).toFixed(1)+' km/h'];"
    "   let tw=0; lines.forEach(t=>{tw=Math.max(tw,g.measureText(t).width);}); const pad=6; const lh=14; const th=pad*2+lines.length*lh;"
    "   let tx=x+10; if(tx+tw+pad*2>c.width-4){tx=x-(tw+pad*2)-10;} if(tx<4){tx=4;} let ty=TOP+8; if(ty+th>c.height-4){ty=c.height-th-4;}"
    "   g.fillStyle='rgba(0,0,0,0.72)'; g.fillRect(tx,ty,tw+pad*2,th); g.strokeStyle=fill; g.strokeRect(tx,ty,tw+pad*2,th); g.fillStyle='#ffffff';"
    "   lines.forEach((t,n)=>g.fillText(t,tx+pad,ty+pad+11+n*lh));"
    " }"
    " g.fillStyle=muted; const from=graphState.start+1; const to=graphState.start+s.length; g.fillText(T('graph_range')+' '+from+'-'+to+' / '+all.length+' ('+T('graph_nav_hint')+')',L+2,c.height-3); if(graphState.error){g.fillStyle='#ff6961'; g.fillText(T('graph_load_error'),L+2,24);}"
    "}"
    "async function drawGraph(){"
    " try{"
    "   const r=await fetch('/api/sessions?ts='+Date.now(),{cache:'no-store'});"
    "   if(!r.ok){graphState.error='http'; renderGraph(); return;}"
    "   const d=await r.json(); const raw=Array.isArray(d&&d.sessions)?d.sessions:[];"
    "   graphState.sessions=raw.filter(x=>x&&typeof x==='object');"
    "   if(graphState.stickLatest){const win=Math.max(10,Math.min(60,graphState.sessions.length)); graphState.start=Math.max(0,graphState.sessions.length-win);}"
    "   graphState.error=''; renderGraph();"
    " }catch(_e){graphState.error='net'; renderGraph();}"
    "}"
    "function initGraphInteraction(){"
    " const c=E('cv'); if(!c||c.dataset.bound==='1') return; c.dataset.bound='1';"
    " const dragMove=ev=>{"
    "   if(!(graphState.drag&&graphState.layout)) return false;"
    "   const p=graphClientPoint(ev); const dx=p.x-graphState.dragX;"
    "   const bars=Math.round((-dx)/Math.max(1,graphState.layout.bw));"
    "   const maxStart=Math.max(0,graphState.sessions.length-graphState.window);"
    "   const ns=clampI(graphState.dragStart+bars,0,maxStart);"
    "   if(ns!==graphState.start){graphState.start=ns; graphState.hover=-1; renderGraph();}"
    "   return true;"
    " };"
    " c.addEventListener('wheel',ev=>{ev.preventDefault(); const maxStart=Math.max(0,graphState.sessions.length-graphState.window); if(maxStart<=0) return; const step=ev.deltaY>0?3:-3; graphState.start=clampI(graphState.start+step,0,maxStart); graphState.hover=-1; graphState.stickLatest=false; renderGraph();},{passive:false});"
    " c.addEventListener('mousedown',ev=>{const p=graphClientPoint(ev); graphState.drag=true; graphState.dragX=p.x; graphState.dragStart=graphState.start; graphState.stickLatest=false;});"
    " window.addEventListener('mouseup',()=>{graphState.drag=false;});"
    " c.addEventListener('mousemove',ev=>{"
    "   if(dragMove(ev)){return;}"
    "   const idx=graphPointerIndex(ev); if(idx!==graphState.hover){graphState.hover=idx; renderGraph();}"
    " });"
    " c.addEventListener('touchstart',ev=>{const p=graphClientPoint(ev); graphState.drag=true; graphState.dragX=p.x; graphState.dragStart=graphState.start; graphState.stickLatest=false;},{passive:true});"
    " c.addEventListener('touchmove',ev=>{if(dragMove(ev)){ev.preventDefault();}},{passive:false});"
    " c.addEventListener('touchend',()=>{graphState.drag=false;});"
    " c.addEventListener('touchcancel',()=>{graphState.drag=false;});"
    " c.addEventListener('mouseleave',()=>{if(!graphState.drag&&graphState.hover!==-1){graphState.hover=-1; renderGraph();}});"
    "}"
    "initGraphInteraction();loadLanguage();tick();drawGraph();setInterval(tick,700);setInterval(drawGraph,3000);"
    "</script></main></body></html>";

static const char k_settings_page[] =
    "<!doctype html><html><head><meta charset='utf-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>Cat Wheel Settings</title>"
    "<style>"
    ":root{--bg:#eef2f7;--surface:#ffffff;--surface2:#f5f8ff;--text:#1b2430;--muted:#5f6e85;--border:#d8e0ef;--accent:#2f6fed;--btn2:#4b5563;}"
    "@media (prefers-color-scheme: dark){:root{--bg:#0f141b;--surface:#171e28;--surface2:#101823;--text:#e8eef7;--muted:#9fb0c7;--border:#2a3648;--accent:#6ea8ff;--btn2:#667389;}}"
    "*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:'Segoe UI',Tahoma,Arial,sans-serif}"
    "main{max-width:980px;margin:0 auto;padding:12px}.top{display:flex;align-items:center;justify-content:space-between;gap:8px}"
    "h2,h3{margin:0 0 10px 0}section{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:12px;margin:10px 0}"
    "label{display:block;font-size:.86rem;color:var(--muted);margin:8px 0 4px}input,select,button{width:100%;padding:9px;border-radius:10px;border:1px solid var(--border);background:var(--surface2);color:var(--text)}"
    "input[type='color']{width:56px;min-width:56px;height:34px;padding:2px}"
    "input[type='checkbox']{width:18px;height:18px;padding:0}"
    "button{background:var(--accent);color:#fff;border:none;font-weight:700;margin-top:10px}button.secondary{background:var(--btn2)}"
    "a.btn{display:inline-block;text-decoration:none;background:var(--btn2);color:#fff;padding:8px 12px;border-radius:10px;font-weight:600}"
    ".hint{font-size:.82rem;color:var(--muted);margin-top:4px}.table-wrap{overflow:auto}"
    ".color-cell{display:flex;align-items:center;gap:8px}.swatch{display:inline-block;width:18px;height:18px;border-radius:4px;border:1px solid var(--border);background:#000}.hex{font-family:Consolas,Monaco,monospace;font-size:.78rem;color:var(--muted);min-width:74px}"
    "table{width:100%;border-collapse:collapse;min-width:560px}td,th{border-bottom:1px solid var(--border);padding:7px;font-size:.85rem;text-align:left}"
    "@media (max-width:700px){main{padding:10px}}"
    "</style></head><body><main>"
    "<div class='top'><h2 data-i18n='settings_title'>Settings</h2><a class='btn' href='/' data-i18n='to_live'>Back to Live</a></div>"
    "<section><h3 data-i18n='wifi_matrix_title'>WiFi and Matrix</h3>"
    "<label data-i18n='language_label'>Language</label><select id='lang'><option value='en' data-i18n='lang_en'>English</option><option value='de' data-i18n='lang_de'>Deutsch</option></select>"
    "<label data-i18n='ssid_label'>SSID</label><input id='ssid'>"
    "<label data-i18n='pass_label'>Password</label><input id='pass' type='password'>"
    "<div class='hint' data-i18n='pass_hint'>Leave empty to keep existing password.</div>"
    "<label data-i18n='matrix_mode_label'>Matrix Mode</label><select id='mode'>"
    "<option value='always' data-i18n='mode_always'>Always</option>"
    "<option value='running_only' data-i18n='mode_running'>Running Only</option>"
    "<option value='auto_timeout' data-i18n='mode_auto'>Auto Off</option>"
    "</select>"
    "<label data-i18n='auto_off_label'>Auto-Off Seconds</label><input id='off' type='number' min='1' max='86400'>"
    "<label data-i18n='mpp_label'>Meters per Pulse</label><input id='mpp' type='number' step='0.0001'>"
    "<label data-i18n='global_bri_label'>Global Brightness (%)</label><input id='global_bri' type='number' min='1' max='100'>"
    "<div class='hint' data-i18n='global_bri_hint'>Used when no brightness window is active.</div>"
    "<div class='table-wrap'><table><thead><tr><th data-i18n='off_window_table'>Display Off Window</th><th data-i18n='col_active'>Active</th><th data-i18n='col_start'>Start</th><th data-i18n='col_end'>End</th></tr></thead><tbody>"
    "<tr><td data-i18n='off_window_row'>Night Mode</td><td><input id='off_window_enabled' type='checkbox'></td><td><input id='off_window_start' type='time'></td><td><input id='off_window_end' type='time'></td></tr>"
    "</tbody></table></div>"
    "<div class='table-wrap'><table><thead><tr><th data-i18n='bw_table'>Brightness Window</th><th data-i18n='col_active'>Active</th><th data-i18n='col_start'>Start</th><th data-i18n='col_end'>End</th><th data-i18n='col_brightness'>Brightness %</th></tr></thead><tbody>"
    "<tr><td data-i18n='bw_row1'>Profile 1</td><td><input id='bw0_enabled' type='checkbox'></td><td><input id='bw0_start' type='time'></td><td><input id='bw0_end' type='time'></td><td><input id='bw0_bri' type='number' min='1' max='100'></td></tr>"
    "<tr><td data-i18n='bw_row2'>Profile 2</td><td><input id='bw1_enabled' type='checkbox'></td><td><input id='bw1_start' type='time'></td><td><input id='bw1_end' type='time'></td><td><input id='bw1_bri' type='number' min='1' max='100'></td></tr>"
    "</tbody></table></div>"
    "<div class='table-wrap'><table><thead><tr><th data-i18n='col_value'>Value</th><th data-i18n='col_on'>On</th><th data-i18n='col_row'>Row</th><th data-i18n='col_color'>Color</th><th data-i18n='col_current'>Current</th></tr></thead><tbody>"
    "<tr><td data-i18n='row_total'>Total</td><td><input id='total_distance_enabled' type='checkbox'></td><td><input id='total_distance_row' type='number' min='0' max='7'></td><td><input id='total_distance_color' type='color'></td><td><div class='color-cell'><span class='swatch' id='total_distance_preview'></span><span class='hex' id='total_distance_hex'>#FFFFFF</span></div></td></tr>"
    "<tr><td data-i18n='row_today'>Today</td><td><input id='distance_today_enabled' type='checkbox'></td><td><input id='distance_today_row' type='number' min='0' max='7'></td><td><input id='distance_today_color' type='color'></td><td><div class='color-cell'><span class='swatch' id='distance_today_preview'></span><span class='hex' id='distance_today_hex'>#FFFFFF</span></div></td></tr>"
    "<tr><td data-i18n='row_top'>Top</td><td><input id='top_speed_enabled' type='checkbox'></td><td><input id='top_speed_row' type='number' min='0' max='7'></td><td><input id='top_speed_color' type='color'></td><td><div class='color-cell'><span class='swatch' id='top_speed_preview'></span><span class='hex' id='top_speed_hex'>#FFFFFF</span></div></td></tr>"
    "<tr><td data-i18n='row_top_today'>Top Today</td><td><input id='top_speed_today_enabled' type='checkbox'></td><td><input id='top_speed_today_row' type='number' min='0' max='7'></td><td><input id='top_speed_today_color' type='color'></td><td><div class='color-cell'><span class='swatch' id='top_speed_today_preview'></span><span class='hex' id='top_speed_today_hex'>#FFFFFF</span></div></td></tr>"
    "<tr><td data-i18n='row_current'>Current</td><td><input id='current_speed_enabled' type='checkbox'></td><td><input id='current_speed_row' type='number' min='0' max='7'></td><td><input id='current_speed_color' type='color'></td><td><div class='color-cell'><span class='swatch' id='current_speed_preview'></span><span class='hex' id='current_speed_hex'>#FFFFFF</span></div></td></tr>"
    "<tr><td data-i18n='row_graph'>Graph</td><td><input id='graph_enabled' type='checkbox'></td><td><input id='graph_row' type='number' min='0' max='7'></td><td><input id='graph_color' type='color'></td><td><div class='color-cell'><span class='swatch' id='graph_preview'></span><span class='hex' id='graph_hex'>#00A0FF</span></div></td></tr>"
    "</tbody></table></div>"
    "<button onclick='saveCfg()' data-i18n='btn_save'>Save</button>"
    "<div id='msg' class='hint'></div>"
    "</section>"
    "<section><h3 data-i18n='backup_title'>Backup</h3>"
    "<button class='secondary' onclick='downloadBackup()' data-i18n='btn_backup_download'>Download Backup</button>"
    "<label data-i18n='backup_file_label'>Backup File</label><input id='backup' type='file' accept='application/json'>"
    "<button onclick='uploadBackup()' data-i18n='btn_backup_upload'>Upload Backup</button>"
    "</section>"
    "<script>"
    "const keys=['total_distance','distance_today','top_speed','top_speed_today','current_speed'];"
    "const colorKeys=[...keys,'graph'];"
    "const E=id=>document.getElementById(id);"
    "const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));"
    "const I18N={"
    "en:{settings_title:'Settings',to_live:'Back to Live',wifi_matrix_title:'WiFi and Matrix',language_label:'Language',lang_en:'English',lang_de:'Deutsch',ssid_label:'SSID',pass_label:'Password',pass_hint:'Leave empty to keep existing password.',"
    "matrix_mode_label:'Matrix Mode',mode_always:'Always',mode_running:'Running Only',mode_auto:'Auto Off',auto_off_label:'Auto-Off Seconds',mpp_label:'Meters per Pulse',global_bri_label:'Global Brightness (%)',global_bri_hint:'Used when no brightness window is active.',"
    "off_window_table:'Display Off Window',col_active:'Active',col_start:'Start',col_end:'End',off_window_row:'Night Mode',bw_table:'Brightness Window',col_brightness:'Brightness %',bw_row1:'Profile 1',bw_row2:'Profile 2',"
    "col_value:'Value',col_on:'On',col_row:'Row',col_color:'Color',col_current:'Current',row_total:'Total',row_today:'Today',row_top:'Top',row_top_today:'Top Today',row_current:'Current',row_graph:'Graph',"
    "btn_save:'Save',backup_title:'Backup',btn_backup_download:'Download Backup',backup_file_label:'Backup File',btn_backup_upload:'Upload Backup',msg_saved:'Saved',msg_error:'Error',msg_imported:'Backup imported',msg_import_error:'Import error'},"
    "de:{settings_title:'Einstellungen',to_live:'Zur Live-Seite',wifi_matrix_title:'WLAN und Matrix',language_label:'Sprache',lang_en:'Englisch',lang_de:'Deutsch',ssid_label:'SSID',pass_label:'Passwort',pass_hint:'Leer lassen = Passwort unveraendert.',"
    "matrix_mode_label:'Matrix Modus',mode_always:'Immer',mode_running:'Nur Lauf',mode_auto:'Auto Off',auto_off_label:'Auto-Off Sekunden',mpp_label:'Meter pro Impuls',global_bri_label:'Globale Helligkeit (%)',global_bri_hint:'Wird genutzt, wenn kein Helligkeitsfenster aktiv ist.',"
    "off_window_table:'Display Aus Zeitfenster',col_active:'Aktiv',col_start:'Start',col_end:'Ende',off_window_row:'Nachtruhe',bw_table:'Helligkeitsfenster',col_brightness:'Helligkeit %',bw_row1:'Profil 1',bw_row2:'Profil 2',"
    "col_value:'Wert',col_on:'An',col_row:'Zeile',col_color:'Farbe',col_current:'Aktuell',row_total:'Total',row_today:'Heute',row_top:'Top',row_top_today:'Top Heute',row_current:'Aktuell',row_graph:'Graph',"
    "btn_save:'Speichern',backup_title:'Backup',btn_backup_download:'Backup Download',backup_file_label:'Backup Datei',btn_backup_upload:'Backup Upload',msg_saved:'Gespeichert',msg_error:'Fehler',msg_imported:'Backup importiert',msg_import_error:'Import Fehler'}};"
    "let LANG='en';"
    "const T=k=>((I18N[LANG]&&I18N[LANG][k])||I18N.en[k]||k);"
    "function applyLanguage(lang){"
    " LANG=(lang==='de')?'de':'en';"
    " localStorage.setItem('cw_lang',LANG);"
    " document.documentElement.lang=LANG;"
    " document.title=(LANG==='de')?'Cat Wheel Einstellungen':'Cat Wheel Settings';"
    " document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.getAttribute('data-i18n'); if(key){el.textContent=T(key);}});"
    "}"
    "function syncColor(k){const c=(E(k+'_color').value||'#ffffff').toUpperCase(); E(k+'_preview').style.background=c; E(k+'_hex').textContent=c;}"
    "function bindColor(k){const el=E(k+'_color'); if(!el) return; el.addEventListener('input',()=>syncColor(k)); el.addEventListener('change',()=>syncColor(k)); syncColor(k);}"
    "function put(c){"
    " E('ssid').value=c.wifi_ssid||''; E('pass').value=''; E('mode').value=c.matrix_mode;"
    " E('off').value=c.auto_off_sec; E('mpp').value=c.meters_per_pulse; E('global_bri').value=(c.global_brightness_pct??80);"
    " E('lang').value=(c.language==='de')?'de':'en';"
    " applyLanguage(E('lang').value);"
    " const ow=c.off_window||{}; E('off_window_enabled').checked=!!ow.enabled; E('off_window_start').value=ow.start||'23:00'; E('off_window_end').value=ow.end||'07:00';"
    " const bw=Array.isArray(c.brightness_windows)?c.brightness_windows:[];"
    " const b0=bw[0]||{}; const b1=bw[1]||{};"
    " E('bw0_enabled').checked=!!b0.enabled; E('bw0_start').value=b0.start||'07:00'; E('bw0_end').value=b0.end||'20:00'; E('bw0_bri').value=(b0.brightness_pct??100);"
    " E('bw1_enabled').checked=!!b1.enabled; E('bw1_start').value=b1.start||'20:00'; E('bw1_end').value=b1.end||'07:00'; E('bw1_bri').value=(b1.brightness_pct??30);"
    " for(const k of keys){const i=c.items[k]; if(!i) continue; E(k+'_enabled').checked=!!i.enabled; E(k+'_row').value=i.row; E(k+'_color').value=i.color||'#ffffff';}"
    " const g=c.graph||{}; E('graph_enabled').checked=!!g.enabled; E('graph_row').value=(g.row??6); E('graph_color').value=g.color||'#00a0ff';"
    " for(const k of colorKeys){syncColor(k);}"
    "}"
    "async function loadCfg(){const r=await fetch('/api/config'); if(r.ok) put(await r.json());}"
    "async function saveCfg(){"
    " const pass=E('pass').value;"
    " const p={wifi_ssid:E('ssid').value.trim(),language:E('lang').value,matrix_mode:E('mode').value,auto_off_sec:parseInt(E('off').value||'45',10),meters_per_pulse:parseFloat(E('mpp').value||'0.7854'),global_brightness_pct:clamp(parseInt(E('global_bri').value||'80',10),1,100),off_window:{enabled:E('off_window_enabled').checked,start:E('off_window_start').value||'23:00',end:E('off_window_end').value||'07:00'},brightness_windows:[{enabled:E('bw0_enabled').checked,start:E('bw0_start').value||'07:00',end:E('bw0_end').value||'20:00',brightness_pct:clamp(parseInt(E('bw0_bri').value||'100',10),1,100)},{enabled:E('bw1_enabled').checked,start:E('bw1_start').value||'20:00',end:E('bw1_end').value||'07:00',brightness_pct:clamp(parseInt(E('bw1_bri').value||'30',10),1,100)}],items:{},graph:{enabled:E('graph_enabled').checked,row:parseInt(E('graph_row').value||'6',10),color:E('graph_color').value}};"
    " if(pass.length>0){p.wifi_pass=pass;}"
    " for(const k of keys){p.items[k]={enabled:E(k+'_enabled').checked,row:parseInt(E(k+'_row').value||'0',10),color:E(k+'_color').value};}"
    " const r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});"
    " E('msg').textContent=r.ok?T('msg_saved'):T('msg_error'); if(r.ok){loadCfg();}"
    "}"
    "async function downloadBackup(){"
    " const r=await fetch('/api/backup'); if(!r.ok) return; const t=await r.text();"
    " const b=new Blob([t],{type:'application/json'}); const u=URL.createObjectURL(b); const a=document.createElement('a');"
    " a.href=u; a.download='catwheel-backup.json'; a.click(); URL.revokeObjectURL(u);"
    "}"
    "async function uploadBackup(){"
    " const f=E('backup').files[0]; if(!f) return; const t=await f.text();"
    " const r=await fetch('/api/backup/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:t});"
    " E('msg').textContent=r.ok?T('msg_imported'):T('msg_import_error'); if(r.ok){loadCfg();}"
    "}"
    "E('lang').addEventListener('change',()=>applyLanguage(E('lang').value));"
    "for(const k of colorKeys){bindColor(k);} "
    "const cached=localStorage.getItem('cw_lang'); if(cached==='de'||cached==='en'){applyLanguage(cached);} "
    "loadCfg();"
    "</script></main></body></html>";

const char *catwheel_get_dashboard_page(void) {
    return k_dashboard_page;
}

const char *catwheel_get_settings_page(void) {
    return k_settings_page;
}
